name: ${project.name}
version: ${project.version}
main: a4.papers.chatfilter.chatfilter.ChatFilter
api-version: 1.21
folia-supported: true
authors: [ A4_Papers ]
description: Basic Regex chat, book and anvil filter
commands:
  chatfilter:
    aliases: [cf]
    description: chatfilter
  clearchat:
    description: clear chat
